meta:
    name: MATEC
    version: 0.1.0
    schema: 1
    
path:
    modules:
        
    system:
        settings:
            settings_yml: system/settings/settings.yml
            backup_yml: system/settings/backup.yml
            default_yml: system/settings/default.yml
        
commands:
    system:
        - settings
        - matec
        - debug
    modules:
        submodulesA:
            - circle
            - kite
            - oval
            - parallelogram
            - rectangle
            - rhombus
            - square
            - trapezoid
            - triangle
        submodulesB:
            - none