meta:
    name: MATEC
    version: 0.2.0

commands:
    system:
        - settings
        - matec
        - debug
    modules:
        submodulesA:
            - circle
            - kite
            - oval
            - parallelogram
            - rectangle
            - rhombus
            - square
            - trapezoid
            - triangle
        submodulesB:
            - none