# MATEC Configuration File
meta:
    name: MATEC
    version: 0.3.0
    author: leverec
    
commands:
    system:
        - clear
        - cls
        - exit
        - q
        - help
        - settings
        - debug
    modules:
        submodulesA:
            - circle
            - rectangle
            - square
            - triangle

modules:
    geometry:
        - circle
        - rectangle
        - square
        - triangle